### ISSUE TITLE
Can you provide the compiled image file？

### ISSUE THREAD

**Issue by BLANK2077** [ussamazahid96/ZC706-PYNQ#1]
My working environment does not allow me to use Linux, so I cannot compile it myself. But I urgently need to use pynq. The version of vivado I use is 2018.3. If it is convenient, you can use cloud disk or other ways to share, thank you very much! My email address is q416366370@foxmail.com

**Comment by ussamazahid96** [comment]
I am sorry, unfortunately I cannot share the image because of copyright issues. The files and steps to build the image are available and you can rebuild easily.
